#!/usr/bin/env bash
# Display listening ports with PID and name
echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"
sudo ss -tulnp | awk '
NR>1 {
if ($1 ~ /tcp|udp/) {
	printf "%-8s %-6s %-6s %-22s %-22s %-10s %s\n", $1, $2, $3, $4, $5, $6, $7
    }
}'
echo -e "\nActive UNIX domain sockets (only servers)"
echo "Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path"
sudo ss -xlnp | awk '
NR>1 {
if ($1 ~ /unix/) {
	printf "%-8s %-6s %-10s %-12s %-12s %-8s %s\n", $1, $2, $3, $4, $5, $6, $7 
	}
}'
